remote_theme: pointbar/minima
title: Bénédicte Lambert
author: Bénédicte Lambert
email: contact@benedictelambert.com
description : Afficher des recettes de cuisine en utilisant des contenus en markdown et un générateur de site jekyll pour la mise en page
github_username: bndct-lmbrt
twitter_username: bndct_lmbrt
youtube_username: bene.lambert
flickr_username: benedicte-lambert
medium_username: bndctlmbrt
